name: Deploy Host to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "host/**"
      - "shared/**"
      - ".github/workflows/deploy-host.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: host
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (root)
        run: npm install
        working-directory: ${{ github.workspace }}

      - name: Install dependencies (host)
        run: npm install

      - name: Build host
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
